[project]
name = "gen-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "guriii08", email = "gurveer.palinfocom@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
gen-ai = "gen_ai:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
